version: "3.5"

networks:
  net-craftbeer:
    name: net-craftbeer
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.62.0.0/24

services:
  postgresql:
    labels:
      br.dev.andreferreira.author: "Andre Ferreira"
      br.dev.andreferreira.description: "Database PostgreSQL Server 13.1 Alpine"
      br.dev.andreferreira.license: "MIT"
    hostname: postgresql-server
    build:
      context: ./docker
      dockerfile: Dockerfile
    env_file:
      - ./docker/.env
    volumes:
      - ./docker/data:/var/lib/postgresql/data/
    expose:
      - 5432
    networks:
      net-craftbeer:
        ipv4_address: "10.62.0.254"